// Bootstrap the topup app from a one-tap link generated by Alby Hub.
//
// The link looks like:
//   https://card.albylabs.com/#label=RedotPay&address=0x...&chainId=42161&currency=USDC&nwc=<urlencoded-pairing-uri>
//
// Why a URL hash (anchor):
//  - Hash fragments are CLIENT-SIDE ONLY — browsers never include them in
//    HTTP requests, so the NWC secret never reaches GitHub Pages / any
//    server log / Referer header.
//  - Never log the nwc value to the console.

import { isAddress } from "viem";
import {
  SUPPORTED_CHAINS,
  SUPPORTED_CURRENCIES,
  type SupportedCurrency,
} from "./lendaswap";
import type { CardConfig } from "./config";

export type HashBootstrap = {
  config: CardConfig | null;
  nwcUri: string | null;
};

// Parse a "#label=…&address=…&chainId=…&currency=…&nwc=…" fragment string
// (with or without a leading '#') into a validated bootstrap object.
// Exported so the clipboard-paste fallback in App.tsx can reuse the exact
// same validation as the URL-based one-tap link.
export function parseBootstrapHash(raw: string): HashBootstrap {
  const empty: HashBootstrap = { config: null, nwcUri: null };
  if (!raw) return empty;

  // Accept either a full URL or just the fragment. If the user copied the
  // whole link from Alby Hub (e.g. on iOS), pluck the part after '#'.
  const hashIndex = raw.indexOf("#");
  const fragment = hashIndex >= 0 ? raw.slice(hashIndex + 1) : raw;
  if (!fragment) return empty;

  const params = new URLSearchParams(fragment);
  if (![...params.keys()].length) return empty;

  // -- Parse config bits (all optional individually, but only commit if the
  //    required ones are present and valid) ------------------------------
  const label = params.get("label") ?? undefined;
  const address = params.get("address");
  const chainIdRaw = params.get("chainId");
  const currencyRaw = params.get("currency");

  let config: CardConfig | null = null;
  if (address && chainIdRaw && currencyRaw) {
    const chainId = Number(chainIdRaw);
    const currency = currencyRaw as SupportedCurrency;
    if (
      isAddress(address) &&
      SUPPORTED_CHAINS.some((c) => c.chainId === chainId) &&
      SUPPORTED_CURRENCIES.includes(currency)
    ) {
      config = {
        label: label?.trim() || undefined,
        destinationAddress: address as `0x${string}`,
        chainId,
        currency,
      };
    }
  }

  // -- NWC URI ----------------------------------------------------------
  // Only accept obviously-shaped values. Don't log this on failure.
  const nwcRaw = params.get("nwc");
  const nwcUri =
    nwcRaw && nwcRaw.startsWith("nostr+walletconnect://") ? nwcRaw : null;

  return { config, nwcUri };
}

export function readHashBootstrap(): HashBootstrap {
  const empty: HashBootstrap = { config: null, nwcUri: null };

  if (typeof window === "undefined") return empty;
  const raw = window.location.hash;
  if (!raw || raw === "#") return empty;

  return parseBootstrapHash(raw);
}
